#!/usr/bin/env node
'use strict';

// PreToolUse(Bash) guard: libs/ is generated by `npm run sync:libs` and must not
// be changed by hand (CLAUDE.md). The settings ask before Edit(./libs/**), but a
// shell write bypasses that — so a Bash command that writes into libs/ is blocked.
// ponytail: a heuristic over the command text; a write through a variable path or a
// script file is not seen — upgrade to a file-system check if that ever happens.

const LIBS = String.raw`(?:^|[\s'"=(])(?:\./)?libs/`;
const WRITES = [
    new RegExp(String.raw`\bsed\s+(?:-\w+\s+)*-i[^;&|\n]*${LIBS}`),
    new RegExp(String.raw`>>?\s*['"]?(?:\./)?libs/`),
    // libs/ as the last argument, i.e. the target — a copy out of libs/ is a read
    new RegExp(String.raw`\b(?:cp|mv|rm|tee|touch|patch)\b[^;&|\n]*${LIBS}[^\s;&|]*\s*(?:$|[;&|])`, 'm'),
];
const WRITE_API = /write_text|writeFileSync|open\([^)]*['"][wa]['"]/;

let raw = '';
process.stdin.on('data', chunk => { raw += chunk; });
process.stdin.on('end', () => {
    const input = JSON.parse(raw || '{}');
    const command = (input.tool_input && input.tool_input.command) || '';
    if (WRITES.some(re => re.test(command)) || (WRITE_API.test(command) && new RegExp(LIBS).test(command))) {
        process.stderr.write('Blocked: libs/ is generated by `npm run sync:libs` from package.json — do not change it by hand (CLAUDE.md, docs/conventions.md).\n');
        process.exit(2);
    }
});
